/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gym_app;

import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.Image;
import java.text.DecimalFormat;
import javax.swing.ImageIcon;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.Document;

/**
 *
 * @author ANDY
 */
public class entrevista_rutina extends javax.swing.JFrame {

    /**
     * Creates new form entrevista_rutinasss
     */
    public entrevista_rutina() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);

        /*IMAGENES*/
        Document doc = imctxt.getDocument();
        doc.addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                actualizarImagen();
                System.out.println("Insert");
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                actualizarImagen();
                System.out.println("Eliminar");
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                actualizarImagen();
                System.out.println("Cambio");
            }

            public void actualizarImagen() {
                try {
                    // Obtener el valor como un número

                    double imc = Double.parseDouble(imctxt.getText());

                    // Determinar qué imagen mostrar según el valor ingresado
                    ImageIcon imagen;
                    if (imc < 18.5) {
                        imagen = new ImageIcon("src/Image/1azul.png");
                        System.out.println("Inserto 1");
                    } else if (imc <= 24.9) {
                        imagen = new ImageIcon("src/Image/2Verde.png");
                        System.out.println("Inserto 2");
                    } else if (imc <= 29.9) {
                        imagen = new ImageIcon("src/Image/3Amarillo.png");
                        System.out.println("Inserto 3");
                    } else if (imc <= 34.9) {
                        imagen = new ImageIcon("src/Image/4Naranja.png");
                        System.out.println("Inserto 4");
                    } else if (imc <= 39.9) {
                        imagen = new ImageIcon("src/Image/5Anaranjado.png");
                        System.out.println("Inserto 5");
                    } else {
                        imagen = new ImageIcon("src/Image/6Rojo.png");
                        System.out.println("Inserto 6");
                    }

                    // Establecer la imagen en el JLabel
                    LabelIMC.setIcon(imagen);
                } catch (NumberFormatException ex) {
                    // En caso de que el texto no sea un número válido, no se actualiza la imagen
                    LabelIMC.setIcon(null);
                    System.out.println(ex);
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fechatxt = new javax.swing.JTextField();
        noControltxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        LPeso = new javax.swing.JLabel();
        LAltura = new javax.swing.JLabel();
        LIMC = new javax.swing.JLabel();
        pesotxt = new javax.swing.JTextField();
        alturatxt = new javax.swing.JTextField();
        imctxt = new javax.swing.JTextField();
        LEdad = new javax.swing.JLabel();
        edadtxt = new javax.swing.JTextField();
        LCondiciones = new javax.swing.JLabel();
        LNivel = new javax.swing.JLabel();
        C1 = new javax.swing.JCheckBox();
        C2 = new javax.swing.JCheckBox();
        L9 = new javax.swing.JCheckBox();
        NivelConFisBOX = new javax.swing.JComboBox<>();
        LLesiones = new javax.swing.JLabel();
        LLimitaciones = new javax.swing.JLabel();
        L1 = new javax.swing.JCheckBox();
        L3 = new javax.swing.JCheckBox();
        C5 = new javax.swing.JCheckBox();
        Lcliente = new javax.swing.JLabel();
        nomClitxt = new javax.swing.JTextField();
        LSexo = new javax.swing.JLabel();
        sexotxt = new javax.swing.JTextField();
        L6 = new javax.swing.JCheckBox();
        L5 = new javax.swing.JCheckBox();
        L2 = new javax.swing.JCheckBox();
        L7 = new javax.swing.JCheckBox();
        L8 = new javax.swing.JCheckBox();
        L4 = new javax.swing.JCheckBox();
        L10 = new javax.swing.JCheckBox();
        C3 = new javax.swing.JCheckBox();
        C4 = new javax.swing.JCheckBox();
        C6 = new javax.swing.JCheckBox();
        LF2 = new javax.swing.JCheckBox();
        LF3 = new javax.swing.JCheckBox();
        LF1 = new javax.swing.JCheckBox();
        LF4 = new javax.swing.JCheckBox();
        LObjetivos = new javax.swing.JLabel();
        Ob1 = new javax.swing.JRadioButton();
        Ob3 = new javax.swing.JRadioButton();
        Ob5 = new javax.swing.JRadioButton();
        Ob2 = new javax.swing.JRadioButton();
        Ob6 = new javax.swing.JRadioButton();
        Ob4 = new javax.swing.JRadioButton();
        LabelIMC = new javax.swing.JLabel();
        LLesionesIma = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Lucida Sans", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Entrevista ");

        fechatxt.setEditable(false);
        fechatxt.setBackground(new java.awt.Color(204, 204, 204));
        fechatxt.setForeground(new java.awt.Color(0, 0, 0));
        fechatxt.setText("09/10/2024");
        fechatxt.setCaretColor(new java.awt.Color(153, 153, 153));
        fechatxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        noControltxt.setEditable(false);
        noControltxt.setBackground(new java.awt.Color(204, 204, 204));
        noControltxt.setForeground(new java.awt.Color(0, 0, 0));
        noControltxt.setText("21550747");
        noControltxt.setCaretColor(new java.awt.Color(153, 153, 153));
        noControltxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(noControltxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(fechatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fechatxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(noControltxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));

        jPanel1.setBackground(new java.awt.Color(242, 242, 242));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LPeso.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        LPeso.setForeground(new java.awt.Color(0, 0, 0));
        LPeso.setText("Peso:");
        jPanel1.add(LPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 62, -1, -1));

        LAltura.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        LAltura.setForeground(new java.awt.Color(0, 0, 0));
        LAltura.setText("Altura:");
        jPanel1.add(LAltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 62, -1, -1));

        LIMC.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        LIMC.setForeground(new java.awt.Color(0, 0, 0));
        LIMC.setText("IMC:");
        jPanel1.add(LIMC, new org.netbeans.lib.awtextra.AbsoluteConstraints(603, 62, -1, -1));

        pesotxt.setText("0");
        jPanel1.add(pesotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 64, 80, -1));

        alturatxt.setText("0");
        alturatxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alturatxtActionPerformed(evt);
            }
        });
        alturatxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                alturatxtKeyReleased(evt);
            }
        });
        jPanel1.add(alturatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 64, 80, -1));

        imctxt.setBackground(new java.awt.Color(204, 204, 204));
        imctxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        imctxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imctxtActionPerformed(evt);
            }
        });
        imctxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                imctxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                imctxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                imctxtKeyTyped(evt);
            }
        });
        jPanel1.add(imctxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 64, 56, -1));

        LEdad.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        LEdad.setForeground(new java.awt.Color(0, 0, 0));
        LEdad.setText("Edad:");
        jPanel1.add(LEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 62, -1, -1));

        edadtxt.setEditable(false);
        edadtxt.setBackground(new java.awt.Color(204, 204, 204));
        edadtxt.setForeground(new java.awt.Color(0, 0, 0));
        edadtxt.setCaretColor(new java.awt.Color(153, 153, 153));
        edadtxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(edadtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 64, 38, -1));

        LCondiciones.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        LCondiciones.setForeground(new java.awt.Color(0, 0, 0));
        LCondiciones.setText("Condiciones médicas crónicas");
        jPanel1.add(LCondiciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 346, -1, -1));

        LNivel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        LNivel.setForeground(new java.awt.Color(0, 0, 0));
        LNivel.setText("Nivel de condicion fisica");
        jPanel1.add(LNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, -1));

        C1.setText("Asma");
        C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C1ActionPerformed(evt);
            }
        });
        jPanel1.add(C1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, -1, -1));

        C2.setText("Artritis");
        C2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C2ActionPerformed(evt);
            }
        });
        jPanel1.add(C2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, -1, -1));

        L9.setText("Desgarro de ligamento cruzado anterior");
        L9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L9ActionPerformed(evt);
            }
        });
        jPanel1.add(L9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 620, -1, -1));

        NivelConFisBOX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Principiante", "Intermedio", "Avanzado" }));
        NivelConFisBOX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NivelConFisBOXActionPerformed(evt);
            }
        });
        NivelConFisBOX.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NivelConFisBOXKeyPressed(evt);
            }
        });
        jPanel1.add(NivelConFisBOX, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 220, 30));

        LLesiones.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        LLesiones.setForeground(new java.awt.Color(0, 0, 0));
        LLesiones.setText("Lesiones previas");
        jPanel1.add(LLesiones, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 346, -1, -1));

        LLimitaciones.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        LLimitaciones.setForeground(new java.awt.Color(0, 0, 0));
        LLimitaciones.setText("Limitaciones físicas");
        jPanel1.add(LLimitaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 490, -1, -1));

        L1.setText("Esguince de tobillo");
        L1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L1ActionPerformed(evt);
            }
        });
        jPanel1.add(L1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 376, -1, -1));

        L3.setText("Dislocación del hombro");
        L3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L3ActionPerformed(evt);
            }
        });
        jPanel1.add(L3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 436, -1, -1));

        C5.setText("Diabetes ");
        C5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C5ActionPerformed(evt);
            }
        });
        jPanel1.add(C5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, -1, -1));

        Lcliente.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Lcliente.setForeground(new java.awt.Color(0, 0, 0));
        Lcliente.setText("Nombre del cliente:");
        jPanel1.add(Lcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 32, -1, -1));

        nomClitxt.setEditable(false);
        nomClitxt.setBackground(new java.awt.Color(204, 204, 204));
        nomClitxt.setForeground(new java.awt.Color(0, 0, 0));
        nomClitxt.setCaretColor(new java.awt.Color(153, 153, 153));
        nomClitxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(nomClitxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 32, 507, -1));

        LSexo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        LSexo.setForeground(new java.awt.Color(0, 0, 0));
        LSexo.setText("Sexo:");
        jPanel1.add(LSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 62, -1, -1));

        sexotxt.setEditable(false);
        sexotxt.setBackground(new java.awt.Color(204, 204, 204));
        sexotxt.setForeground(new java.awt.Color(0, 0, 0));
        sexotxt.setText("M");
        sexotxt.setCaretColor(new java.awt.Color(153, 153, 153));
        sexotxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(sexotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 64, 38, -1));

        L6.setText("Fractura de muñeca");
        L6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L6ActionPerformed(evt);
            }
        });
        jPanel1.add(L6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 526, -1, -1));

        L5.setText("Hernia discal ");
        L5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L5ActionPerformed(evt);
            }
        });
        jPanel1.add(L5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 496, -1, -1));

        L2.setText("Tendinitis rotuliana");
        L2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L2ActionPerformed(evt);
            }
        });
        jPanel1.add(L2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 406, -1, -1));

        L7.setText("Fractura de clavícula ");
        L7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L7ActionPerformed(evt);
            }
        });
        jPanel1.add(L7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, -1, -1));

        L8.setText("Distensión muscular del cuello");
        L8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L8ActionPerformed(evt);
            }
        });
        jPanel1.add(L8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, -1, -1));

        L4.setText("Desgarro del tendón de Aquiles");
        L4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L4ActionPerformed(evt);
            }
        });
        jPanel1.add(L4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 466, -1, -1));

        L10.setText("Ninguno");
        L10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L10ActionPerformed(evt);
            }
        });
        jPanel1.add(L10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 650, 88, -1));

        C3.setText("Hipertensión");
        C3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C3ActionPerformed(evt);
            }
        });
        jPanel1.add(C3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, -1, -1));

        C4.setText("EPOC");
        C4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C4ActionPerformed(evt);
            }
        });
        jPanel1.add(C4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, -1, -1));

        C6.setText("Ninguno");
        C6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C6ActionPerformed(evt);
            }
        });
        jPanel1.add(C6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 420, -1, -1));

        LF2.setText("Síndrome del túnel carpiano");
        LF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LF2ActionPerformed(evt);
            }
        });
        jPanel1.add(LF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 550, -1, -1));

        LF3.setText("Contractura del músculo trapecio");
        LF3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LF3ActionPerformed(evt);
            }
        });
        jPanel1.add(LF3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 580, -1, -1));

        LF1.setText("Epicondilitis lateral");
        LF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LF1ActionPerformed(evt);
            }
        });
        jPanel1.add(LF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 520, -1, -1));

        LF4.setText("Ninguno");
        LF4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LF4ActionPerformed(evt);
            }
        });
        jPanel1.add(LF4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 610, -1, -1));

        LObjetivos.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        LObjetivos.setForeground(new java.awt.Color(0, 0, 0));
        LObjetivos.setText("Objetivos de fitness");
        jPanel1.add(LObjetivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 94, -1, -1));

        Ob1.setText("Perder peso");
        jPanel1.add(Ob1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 136, -1, -1));

        Ob3.setText("Ganar masa muscular");
        jPanel1.add(Ob3, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 204, -1, -1));

        Ob5.setText("Mejorar mi rendimiento deportivo");
        Ob5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ob5ActionPerformed(evt);
            }
        });
        jPanel1.add(Ob5, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 272, -1, -1));

        Ob2.setText("Mejorar mi salud");
        jPanel1.add(Ob2, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 170, 132, -1));

        Ob6.setText("Mejorar mi resistencia cardiovascular");
        jPanel1.add(Ob6, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 306, 243, -1));

        Ob4.setText("Aumento de la flexibilidad");
        jPanel1.add(Ob4, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 238, -1, -1));

        LabelIMC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/1azul.png"))); // NOI18N
        jPanel1.add(LabelIMC, new org.netbeans.lib.awtextra.AbsoluteConstraints(719, 2, 400, 940));
        jPanel1.add(LLesionesIma, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 680, 550, 260));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1126, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alturatxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alturatxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alturatxtActionPerformed

    private void alturatxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_alturatxtKeyReleased
        // TODO add your handling code here:

        double peso = Double.parseDouble(pesotxt.getText());
        double altura = Double.parseDouble(alturatxt.getText());

        double imc = peso / (altura * altura);
        DecimalFormat formato = new DecimalFormat("#.##");
        String numeroFormateado = formato.format(imc);

        imctxt.setText(numeroFormateado);

    }//GEN-LAST:event_alturatxtKeyReleased

    private void imctxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imctxtActionPerformed
        // TODO add your handling code here:(

            /*
            try {
                double imc = Double.parseDouble(imctxt.getText());
                if (imc < 18.5) {
                    /*Bajo Peso*//*
                    LabelIMC.setIcon(new ImageIcon("Image/1azul.jpg"));
                } else if (imc <= 18.5 && imc >= 24.9) {

                    LabelIMC.setIcon(new ImageIcon("Image/2Verde.jpg"));
                } else if (imc <= 25.0 && imc >= 29.9) {

                    LabelIMC.setIcon(new ImageIcon("Image/3Amarillo.jpg"));
                } else if (imc <= 30.0 && imc >= 34.9) {

                    LabelIMC.setIcon(new ImageIcon("Image/4Naranja.jpg"));
                } else if (imc <= 35.0 && imc >= 39.9) {

                    LabelIMC.setIcon(new ImageIcon("Image/5Anaranjado.jpg"));
                } else if (imc > 40) {

                    LabelIMC.setIcon(new ImageIcon("Image/6Rojo.jpg"));
                }
            } catch (Exception e) {
                System.out.println(e);
            }
            */

    }//GEN-LAST:event_imctxtActionPerformed

    private void imctxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_imctxtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_imctxtKeyPressed

    private void imctxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_imctxtKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_imctxtKeyReleased

    private void imctxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_imctxtKeyTyped

    }//GEN-LAST:event_imctxtKeyTyped

    private void C1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C1ActionPerformed
        // TODO add your handling code here:
        try {
            ImageIcon icon = new ImageIcon("src/Image/C1.jpg"); // Cambia la ruta por la de tu imagen
            // Escalar la imagen al tamaño del JLabel
            Image images = icon.getImage().getScaledInstance(LLesionesIma.getWidth(), LLesionesIma.getHeight(), Image.SCALE_SMOOTH);

            // Crear un ImageIcon con la imagen escalada
            ImageIcon imagen = new ImageIcon(images);

            //    ImageIcon imagen = new ImageIcon("src/Image/C1.jpg");
            LLesionesIma.setIcon(imagen);
        } catch (Exception e) {
            System.err.println("Error al cargar la imagen: " + e.getMessage());
        }
    }//GEN-LAST:event_C1ActionPerformed

    private void C2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C2ActionPerformed
        // TODO add your handling code here:
        try {

            ImageIcon icon = new ImageIcon("src/Image/C2.jpg"); // Cambia la ruta por la de tu imagen
            // Escalar la imagen al tamaño del JLabel
            Image images = icon.getImage().getScaledInstance(LLesionesIma.getWidth(), LLesionesIma.getHeight(), Image.SCALE_SMOOTH);

            // Crear un ImageIcon con la imagen escalada
            ImageIcon imagen = new ImageIcon(images);
            LLesionesIma.setIcon(imagen);
        } catch (Exception e) {
            System.err.println("Error al cargar la imagen: " + e.getMessage());
        }
    }//GEN-LAST:event_C2ActionPerformed

    private void L9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L9ActionPerformed
        // TODO add your handling code here:
        try {

            ImageIcon imagen = new ImageIcon("src/Image/L9.jpg");
            LLesionesIma.setIcon(imagen);
        } catch (Exception e) {
            System.err.println("Error al cargar la imagen: " + e.getMessage());
        }
    }//GEN-LAST:event_L9ActionPerformed

    private void NivelConFisBOXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NivelConFisBOXActionPerformed

    }//GEN-LAST:event_NivelConFisBOXActionPerformed

    private void NivelConFisBOXKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NivelConFisBOXKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_NivelConFisBOXKeyPressed

    private void L1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L1ActionPerformed
        // TODO add your handling code here:
        try {

            ImageIcon imagen = new ImageIcon("src/Image/L1.jpg");
            LLesionesIma.setIcon(imagen);

        } catch (Exception e) {
            System.err.println("Error al cargar la imagen: " + e.getMessage());
        }
    }//GEN-LAST:event_L1ActionPerformed

    private void L3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L3ActionPerformed
        // TODO add your handling code here:
        try {
            if (!L3.isSelected()) {
                //    LLesionesIma.setIcon(null);
            } else {
                ImageIcon imagen = new ImageIcon("src/Image/L3.jpg");
                LLesionesIma.setIcon(imagen);
                //    System.out.println("L3");
            }

        } catch (Exception e) {
            System.err.println("Error al cargar la imagen: " + e.getMessage());
        }
    }//GEN-LAST:event_L3ActionPerformed

    private void C5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C5ActionPerformed
        // TODO add your handling code here:
        try {

            ImageIcon icon = new ImageIcon("src/Image/C5.jpg"); // Cambia la ruta por la de tu imagen
            // Escalar la imagen al tamaño del JLabel
            Image images = icon.getImage().getScaledInstance(LLesionesIma.getWidth(), LLesionesIma.getHeight(), Image.SCALE_SMOOTH);

            // Crear un ImageIcon con la imagen escalada
            ImageIcon imagen = new ImageIcon(images);
            LLesionesIma.setIcon(imagen);
        } catch (Exception e) {
            System.err.println("Error al cargar la imagen: " + e.getMessage());
        }
    }//GEN-LAST:event_C5ActionPerformed

    private void L6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L6ActionPerformed
        // TODO add your handling code here:

        try {

            ImageIcon imagen = new ImageIcon("src/Image/L6.jpg");
            LLesionesIma.setIcon(imagen);
        } catch (Exception e) {
            System.err.println("Error al cargar la imagen: " + e.getMessage());
        }
    }//GEN-LAST:event_L6ActionPerformed

    private void L5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L5ActionPerformed
        // TODO add your handling code here:

        try {

            ImageIcon imagen = new ImageIcon("src/Image/L5.jpg");
            LLesionesIma.setIcon(imagen);
        } catch (Exception e) {
            System.err.println("Error al cargar la imagen: " + e.getMessage());
        }
    }//GEN-LAST:event_L5ActionPerformed

    private void L2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L2ActionPerformed
        // TODO add your handling code here:

        try {

            ImageIcon imagen = new ImageIcon("src/Image/L2.jpg");
            LLesionesIma.setIcon(imagen);
            //    System.out.println("L2");

        } catch (Exception e) {
            System.err.println("Error al cargar la imagen: " + e.getMessage());
        }
    }//GEN-LAST:event_L2ActionPerformed

    private void L7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L7ActionPerformed
        // TODO add your handling code here:

        try {

            ImageIcon imagen = new ImageIcon("src/Image/L7.jpg");
            LLesionesIma.setIcon(imagen);
        } catch (Exception e) {
            System.err.println("Error al cargar la imagen: " + e.getMessage());
        }
    }//GEN-LAST:event_L7ActionPerformed

    private void L8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L8ActionPerformed
        // TODO add your handling code here:

        try {

            ImageIcon imagen = new ImageIcon("src/Image/L8.jpg");
            LLesionesIma.setIcon(imagen);
        } catch (Exception e) {
            System.err.println("Error al cargar la imagen: " + e.getMessage());
        }
    }//GEN-LAST:event_L8ActionPerformed

    private void L4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L4ActionPerformed
        // TODO add your handling code here:
        try {

            ImageIcon imagen = new ImageIcon("src/Image/L4.jpg");
            LLesionesIma.setIcon(imagen);
        } catch (Exception e) {
            System.err.println("Error al cargar la imagen: " + e.getMessage());
        }

    }//GEN-LAST:event_L4ActionPerformed

    private void L10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L10ActionPerformed
        // TODO add your handling code here:
        LLesionesIma.setIcon(null);

        L1.setSelected(false);

        L2.setSelected(false);

        L3.setSelected(false);

        L4.setSelected(false);

        L5.setSelected(false);

        L6.setSelected(false);

        L7.setSelected(false);

        L8.setSelected(false);

        L9.setSelected(false);

    }//GEN-LAST:event_L10ActionPerformed

    private void C3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C3ActionPerformed
        // TODO add your handling code here:
        C3.enable();
        try {

            ImageIcon icon = new ImageIcon("src/Image/C3.png"); // Cambia la ruta por la de tu imagen
            // Escalar la imagen al tamaño del JLabel
            Image images = icon.getImage().getScaledInstance(LLesionesIma.getWidth(), LLesionesIma.getHeight(), Image.SCALE_SMOOTH);

            // Crear un ImageIcon con la imagen escalada
            ImageIcon imagen = new ImageIcon(images);
            LLesionesIma.setIcon(imagen);
        } catch (Exception e) {
            System.err.println("Error al cargar la imagen: " + e.getMessage());
        }
    }//GEN-LAST:event_C3ActionPerformed

    private void C4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C4ActionPerformed
        // TODO add your handling code here:
        try {

            ImageIcon icon = new ImageIcon("src/Image/C4.jpg"); // Cambia la ruta por la de tu imagen
            // Escalar la imagen al tamaño del JLabel
            Image images = icon.getImage().getScaledInstance(LLesionesIma.getWidth(), LLesionesIma.getHeight(), Image.SCALE_SMOOTH);

            // Crear un ImageIcon con la imagen escalada
            ImageIcon imagen = new ImageIcon(images);
            LLesionesIma.setIcon(imagen);
        } catch (Exception e) {
            System.err.println("Error al cargar la imagen: " + e.getMessage());
        }
    }//GEN-LAST:event_C4ActionPerformed

    private void C6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C6ActionPerformed
        // TODO add your handling code here:
        LLesionesIma.setIcon(null);
        C1.setSelected(false);
        C2.setSelected(false);
        C3.setSelected(false);
        C4.setSelected(false);
        C5.setSelected(false);
        C1.enable(false);
        C2.enable(false);
        C3.enable(false);
        C4.enable(false);
        C5.enable(false);

    }//GEN-LAST:event_C6ActionPerformed

    private void LF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LF2ActionPerformed
        // TODO add your handling code here:
        try {

            ImageIcon imagen = new ImageIcon("src/Image/LF2.jpg");
            LLesionesIma.setIcon(imagen);
        } catch (Exception e) {
            System.err.println("Error al cargar la imagen: " + e.getMessage());
        }
    }//GEN-LAST:event_LF2ActionPerformed

    private void LF3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LF3ActionPerformed
        // TODO add your handling code here:
        try {

            ImageIcon imagen = new ImageIcon("src/Image/LF3.jpg");
            LLesionesIma.setIcon(imagen);
        } catch (Exception e) {
            System.err.println("Error al cargar la imagen: " + e.getMessage());
        }
    }//GEN-LAST:event_LF3ActionPerformed

    private void LF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LF1ActionPerformed
        // TODO add your handling code here:
        try {

            ImageIcon imagen = new ImageIcon("src/Image/LF1.jpg");
            LLesionesIma.setIcon(imagen);
        } catch (Exception e) {
            System.err.println("Error al cargar la imagen: " + e.getMessage());
        }
    }//GEN-LAST:event_LF1ActionPerformed

    private void LF4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LF4ActionPerformed
        // TODO add your handling code here:
        LLesionesIma.setIcon(null);
        LF1.setSelected(false);
        LF2.setSelected(false);
        LF3.setSelected(false);

    }//GEN-LAST:event_LF4ActionPerformed

    private void Ob5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ob5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ob5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(entrevista_rutina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(entrevista_rutina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(entrevista_rutina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(entrevista_rutina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new entrevista_rutina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox C1;
    private javax.swing.JCheckBox C2;
    private javax.swing.JCheckBox C3;
    private javax.swing.JCheckBox C4;
    private javax.swing.JCheckBox C5;
    private javax.swing.JCheckBox C6;
    private javax.swing.JCheckBox L1;
    private javax.swing.JCheckBox L10;
    private javax.swing.JCheckBox L2;
    private javax.swing.JCheckBox L3;
    private javax.swing.JCheckBox L4;
    private javax.swing.JCheckBox L5;
    private javax.swing.JCheckBox L6;
    private javax.swing.JCheckBox L7;
    private javax.swing.JCheckBox L8;
    private javax.swing.JCheckBox L9;
    private javax.swing.JLabel LAltura;
    private javax.swing.JLabel LCondiciones;
    private javax.swing.JLabel LEdad;
    private javax.swing.JCheckBox LF1;
    private javax.swing.JCheckBox LF2;
    private javax.swing.JCheckBox LF3;
    private javax.swing.JCheckBox LF4;
    private javax.swing.JLabel LIMC;
    private javax.swing.JLabel LLesiones;
    private javax.swing.JLabel LLesionesIma;
    private javax.swing.JLabel LLimitaciones;
    private javax.swing.JLabel LNivel;
    private javax.swing.JLabel LObjetivos;
    private javax.swing.JLabel LPeso;
    private javax.swing.JLabel LSexo;
    private javax.swing.JLabel LabelIMC;
    private javax.swing.JLabel Lcliente;
    private javax.swing.JComboBox<String> NivelConFisBOX;
    private javax.swing.JRadioButton Ob1;
    private javax.swing.JRadioButton Ob2;
    private javax.swing.JRadioButton Ob3;
    private javax.swing.JRadioButton Ob4;
    private javax.swing.JRadioButton Ob5;
    private javax.swing.JRadioButton Ob6;
    private javax.swing.JTextField alturatxt;
    private javax.swing.JTextField edadtxt;
    private javax.swing.JTextField fechatxt;
    private javax.swing.JTextField imctxt;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField noControltxt;
    private javax.swing.JTextField nomClitxt;
    private javax.swing.JTextField pesotxt;
    private javax.swing.JTextField sexotxt;
    // End of variables declaration//GEN-END:variables
}
