/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gym_app;

import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent; 
import javax.swing.event.DocumentListener;
import javax.swing.text.Document;

/**
 *

 */
public class Horarios extends javax.swing.JFrame {

    /**
     * Creates new form Rutinas
     */
    public Horarios() throws FontFormatException, IOException {
        initComponents();     
        panelh1.setVisible(false);
        panelh2.setVisible(false);
        //this.setLocationRelativeTo(this);
        

        
       

 
        /*IMAGENES*/
       /* Document doc = imctxt.getDocument();
        doc.addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                actualizarImagen();
                System.out.println("Insert");
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                actualizarImagen();
                System.out.println("Eliminar");
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                actualizarImagen();
                System.out.println("Cambio");
            }

            public void actualizarImagen() {
                try {
                    // Obtener el valor como un número

                    double imc = Double.parseDouble(imctxt.getText());

                    // Determinar qué imagen mostrar según el valor ingresado
                    ImageIcon imagen;
                    if (imc < 18.5) {
                        imagen = new ImageIcon("src/Image/1azul.png");
                        System.out.println("Inserto 1");
                    } else if (imc <= 24.9) {
                        imagen = new ImageIcon("src/Image/2Verde.png");
                        System.out.println("Inserto 2");
                    } else if (imc <= 29.9) {
                        imagen = new ImageIcon("src/Image/3Amarillo.png");
                        System.out.println("Inserto 3");
                    } else if (imc <= 34.9) {
                        imagen = new ImageIcon("src/Image/4Naranja.png");
                        System.out.println("Inserto 4");
                    } else if (imc <= 39.9) {
                        imagen = new ImageIcon("src/Image/5Anaranjado.png");
                        System.out.println("Inserto 5");
                    } else {
                        imagen = new ImageIcon("src/Image/6Rojo.png");
                        System.out.println("Inserto 6");
                    }

                    // Establecer la imagen en el JLabel
                    LabelIMC.setIcon(imagen);
                } catch (NumberFormatException ex) {
                    // En caso de que el texto no sea un número válido, no se actualiza la imagen
                    LabelIMC.setIcon(null);
                    System.out.println(ex);
                }
            }
        });
*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fechatxt = new javax.swing.JTextField();
        noControltxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        Lcliente = new javax.swing.JLabel();
        membrhtxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        datostxt = new javax.swing.JTextArea();
        buscarhbtn = new javax.swing.JButton();
        panelh1 = new javax.swing.JPanel();
        nhorariotxt = new javax.swing.JTextField();
        confhorariobtn = new javax.swing.JButton();
        Lcliente3 = new javax.swing.JLabel();
        Lcliente2 = new javax.swing.JLabel();
        nombrehtxt = new javax.swing.JTextField();
        cambiarhobtn = new javax.swing.JButton();
        panelh2 = new javax.swing.JPanel();
        confhbtn = new javax.swing.JButton();
        Lcliente1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        mhorariotxt = new javax.swing.JTextArea();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(244, 246, 248));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setExtendedState(MAXIMIZED_BOTH);
        setLocationByPlatform(true);
        setMaximizedBounds(new java.awt.Rectangle(600, 590, 590, 590));
        setMaximumSize(new java.awt.Dimension(600, 590));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Lucida Sans", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Horarios");

        fechatxt.setEditable(false);
        fechatxt.setBackground(new java.awt.Color(204, 204, 204));
        fechatxt.setText("09/10/2024");
        fechatxt.setCaretColor(new java.awt.Color(153, 153, 153));
        fechatxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        noControltxt.setEditable(false);
        noControltxt.setBackground(new java.awt.Color(204, 204, 204));
        noControltxt.setText("21550747");
        noControltxt.setCaretColor(new java.awt.Color(153, 153, 153));
        noControltxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 217, Short.MAX_VALUE)
                .addComponent(noControltxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(fechatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fechatxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(noControltxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(242, 242, 242));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setMaximumSize(new java.awt.Dimension(600, 590));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Lcliente.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Lcliente.setText("Membresía");
        jPanel1.add(Lcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, -1, -1));

        membrhtxt.setBackground(new java.awt.Color(204, 204, 204));
        membrhtxt.setCaretColor(new java.awt.Color(153, 153, 153));
        membrhtxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(membrhtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 280, -1));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/membresia.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 230, 140));

        datostxt.setEditable(false);
        datostxt.setColumns(20);
        datostxt.setRows(5);
        jScrollPane2.setViewportView(datostxt);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 280, 140));

        buscarhbtn.setText("Buscar");
        buscarhbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buscarhbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarhbtnActionPerformed(evt);
            }
        });
        jPanel1.add(buscarhbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        nhorariotxt.setBackground(new java.awt.Color(204, 204, 204));
        nhorariotxt.setCaretColor(new java.awt.Color(153, 153, 153));
        nhorariotxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        confhorariobtn.setText("Confirmar");
        confhorariobtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        confhorariobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confhorariobtnActionPerformed(evt);
            }
        });

        Lcliente3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Lcliente3.setText("Ingresar horario a elegir:");

        javax.swing.GroupLayout panelh1Layout = new javax.swing.GroupLayout(panelh1);
        panelh1.setLayout(panelh1Layout);
        panelh1Layout.setHorizontalGroup(
            panelh1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelh1Layout.createSequentialGroup()
                .addGap(0, 169, Short.MAX_VALUE)
                .addComponent(confhorariobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelh1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nhorariotxt)
                .addContainerGap())
            .addGroup(panelh1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelh1Layout.createSequentialGroup()
                    .addContainerGap(22, Short.MAX_VALUE)
                    .addComponent(Lcliente3)
                    .addContainerGap()))
        );
        panelh1Layout.setVerticalGroup(
            panelh1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelh1Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(nhorariotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(confhorariobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelh1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelh1Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(Lcliente3)
                    .addContainerGap(86, Short.MAX_VALUE)))
        );

        jPanel1.add(panelh1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 250, 120));

        Lcliente2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Lcliente2.setText("Nombre completo");
        jPanel1.add(Lcliente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, -1, -1));

        nombrehtxt.setBackground(new java.awt.Color(204, 204, 204));
        nombrehtxt.setCaretColor(new java.awt.Color(153, 153, 153));
        nombrehtxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(nombrehtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 380, -1));

        cambiarhobtn.setText("Cambiar Horario");
        cambiarhobtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cambiarhobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarhobtnActionPerformed(evt);
            }
        });
        jPanel1.add(cambiarhobtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, -1, -1));

        confhbtn.setText("Confirmar");
        confhbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        confhbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confhbtnActionPerformed(evt);
            }
        });

        Lcliente1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Lcliente1.setText("Nuevo horario elegido:");

        mhorariotxt.setEditable(false);
        mhorariotxt.setColumns(20);
        mhorariotxt.setRows(5);
        mhorariotxt.setText("\n");
        jScrollPane3.setViewportView(mhorariotxt);

        javax.swing.GroupLayout panelh2Layout = new javax.swing.GroupLayout(panelh2);
        panelh2.setLayout(panelh2Layout);
        panelh2Layout.setHorizontalGroup(
            panelh2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelh2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelh2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelh2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(confhbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelh2Layout.createSequentialGroup()
                        .addGroup(panelh2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lcliente1)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 77, Short.MAX_VALUE))))
        );
        panelh2Layout.setVerticalGroup(
            panelh2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelh2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelh2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelh2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(confhbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelh2Layout.createSequentialGroup()
                        .addComponent(Lcliente1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(39, Short.MAX_VALUE))))
        );

        jPanel1.add(panelh2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 290, 190));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confhbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confhbtnActionPerformed
        JOptionPane.showMessageDialog(null,"Horario confirmado con exito");
        String horario = nhorariotxt.getText();
        String n="";
        if(horario.contains(",")){
            String a[] =new String[horario.length()];
            for(int i=0;i<horario.length();i++){

                a[i] = ""+horario.charAt(i);
                if(a[i].equals(",")){
                    n = n +"\n";
                }else{
                    n = n + horario.charAt(i)+"";
                }
            }
        }else{
            n=horario;
        }
        String nom = nombrehtxt.getText();
        String memb = membrhtxt.getText();
        datostxt.setText(nom+"\n"+memb+"\n"+n);
    }//GEN-LAST:event_confhbtnActionPerformed

    private void cambiarhobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarhobtnActionPerformed
        panelh1.setVisible(true);
        panelh2.setVisible(true);
    }//GEN-LAST:event_cambiarhobtnActionPerformed

    private void confhorariobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confhorariobtnActionPerformed
        String n="";

        String horario = nhorariotxt.getText();
        /*if(horario.contains(",")){
            String a[] =new String[horario.length()];
            for(int i=0;i<horario.length();i++){

                a[i] = ""+horario.charAt(i);
                if(a[i].equals(",")){
                    n = n +"\nsin horario  ->  ";
                }else{
                    n = n + horario.charAt(i)+"";
                }
            }
        }else{
            n=horario;
        }
        */  //CODIGO FUNCIONAL DE PRUEBA DEL HORARIO
        // mhorariotxt.setText("sin horario "+"  ->  "+n);
        exclusivoKaren g = new exclusivoKaren();
        String datos_e = g.leer_horario(membrhtxt.getText(),horario);
        mhorariotxt.setText(datos_e);

    }//GEN-LAST:event_confhorariobtnActionPerformed

    private void buscarhbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarhbtnActionPerformed
        String nom = nombrehtxt.getText();
        String memb = membrhtxt.getText();

        //datostxt.setText(nom+"\n"+memb+"\n sin horario\n");

        String rutaProyecto = System.getProperty("user.dir");
        String archivo= rutaProyecto+"\\src\\Doc\\"+memb+".txt"; 
        exclusivoKaren g = new exclusivoKaren();
        String datos_e = g.leer(memb);

        datostxt.setText(datos_e);

    }//GEN-LAST:event_buscarhbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Horarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Horarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Horarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Horarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Horarios().setVisible(true);
                } catch (FontFormatException ex) {
                    Logger.getLogger(Horarios.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Horarios.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lcliente;
    private javax.swing.JLabel Lcliente1;
    private javax.swing.JLabel Lcliente2;
    private javax.swing.JLabel Lcliente3;
    private javax.swing.JButton buscarhbtn;
    private javax.swing.JButton cambiarhobtn;
    private javax.swing.JButton confhbtn;
    private javax.swing.JButton confhorariobtn;
    private javax.swing.JTextArea datostxt;
    private javax.swing.JTextField fechatxt;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField membrhtxt;
    private javax.swing.JTextArea mhorariotxt;
    private javax.swing.JTextField nhorariotxt;
    private javax.swing.JTextField noControltxt;
    private javax.swing.JTextField nombrehtxt;
    private javax.swing.JPanel panelh1;
    private javax.swing.JPanel panelh2;
    // End of variables declaration//GEN-END:variables
}
