/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gym_app;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author ANDY
 */
public class opciones_login extends javax.swing.JFrame {

    /**
     * Creates new form INICIO
     */
    ImageIcon icon;
    ImageIcon imagen;
    

 
 public opciones_login() {
        initComponents();
       // setExtendedState(MAXIMIZED_BOTH);
        
        this.setLocationRelativeTo(null);
        
        SetImageButton("src/Image/deshacer.png",Regresar);
        SetImageButton("src/Image/Cliente.png",CLIENTE);
        SetImageButton("src/Image/Empleado.png",EMPLEADO);
       

        
      
    }

    
   
    private void SetImageButton(String url,  JButton boton) {
        ImageIcon image = new ImageIcon(url);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(boton.getWidth(), boton.getHeight(), Image.SCALE_SMOOTH));
        boton.setIcon(icon);
       
        
        boton.setBorderPainted(false);
        boton.setContentAreaFilled(false);
        boton.setFocusPainted(false);
        boton.setOpaque(false);
        this.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        CLIENTE = new javax.swing.JButton();
        EMPLEADO = new javax.swing.JButton();
        Regresar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(232, 232, 232));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Eras Demi ITC", 1, 100)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 145, 77));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Eres?");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, -1, -1));

        jLabel6.setFont(new java.awt.Font("Eras Demi ITC", 0, 60)); // NOI18N
        jLabel6.setText("¿Que tipo de usuario");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 1070, 10));

        CLIENTE.setText("CLIENTE");
        CLIENTE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CLIENTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLIENTEActionPerformed(evt);
            }
        });
        jPanel2.add(CLIENTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 311, 287));

        EMPLEADO.setText("EMPLEADO");
        EMPLEADO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EMPLEADO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EMPLEADOActionPerformed(evt);
            }
        });
        jPanel2.add(EMPLEADO, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 210, 311, 287));

        Regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/deshacer.png"))); // NOI18N
        Regresar.setBorder(null);
        Regresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });
        jPanel2.add(Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 41, 37));

        jLabel7.setFont(new java.awt.Font("Eras Demi ITC", 1, 60)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 145, 77));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Empleado");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 520, -1, -1));

        jLabel8.setFont(new java.awt.Font("Eras Demi ITC", 1, 60)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 145, 77));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Cliente");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 520, 265, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CLIENTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLIENTEActionPerformed
       registro_usuario cliente= new registro_usuario();
       cliente.setVisible(true);
       this.setVisible(false);
        
        
    }//GEN-LAST:event_CLIENTEActionPerformed

    private void EMPLEADOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EMPLEADOActionPerformed
            
        RDE empelado= new RDE();
       empelado.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_EMPLEADOActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        // TODO add your handling code here:
        login login = new login();
        login.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_RegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(opciones_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(opciones_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(opciones_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(opciones_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new opciones_login().setVisible(true);
            }
        });
    }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CLIENTE;
    private javax.swing.JButton EMPLEADO;
    private javax.swing.JButton Regresar;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
