/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gym_app;

import java.awt.BorderLayout;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author ANDY
 */
public class Perfil_Empleado extends javax.swing.JFrame {

    /**
     * Creates new form INICIO
     */
    ImageIcon icon;
    ImageIcon imagen;
    
  private JPanelConFondo fondo;

 
 public Perfil_Empleado() {
     setUndecorated(true);
        initComponents();
       // setExtendedState(MAXIMIZED_BOTH);
      
        
        this.setLocationRelativeTo(null);
        
        // this.setContentPane(fondo);
        fondo = new JPanelConFondo("src/Image/perfilF.png");
        FondoP.setLayout(new BorderLayout());
        FondoP.add(fondo);
       
        /*disneo de botnes*/
         SetImageButton2("src/Image/X.png", Salir);
        SetImageButton("src/Image/CompraGYM.png",Comprabtn);
        SetImageButton("src/Image/VentaGYM.png",Ventabtn);
        SetImageButton("src/Image/Cliente.png",AltaCl);
        SetImageButton("src/Image/Empleado.png",AltaEm);
        SetImageButton("src/Image/SeguiEntre.png",SeguiEn);
        SetImageButton("src/Image/Grupal.png",Grupalbtn);
        
        


        
      
    }
        
 
    
   
    private void SetImageButton(String url,  JButton boton) {
        ImageIcon image = new ImageIcon(url);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(boton.getWidth(), boton.getHeight(), Image.SCALE_SMOOTH));
        boton.setIcon(icon);
       
        
     //   boton.setBorderPainted(false);
      //  boton.setContentAreaFilled(false);
        boton.setFocusPainted(false);
    //    boton.setOpaque(false);
        this.repaint();
    }
    private void SetImageButton2(String url,  JButton boton) {
        ImageIcon image = new ImageIcon(url);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(boton.getWidth(), boton.getHeight(), Image.SCALE_SMOOTH));
        boton.setIcon(icon);
       
        
     boton.setBorderPainted(false);
       boton.setContentAreaFilled(false);
        boton.setFocusPainted(false);
      boton.setOpaque(false);
        this.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        AltaCl = new javax.swing.JButton();
        Comprabtn = new javax.swing.JButton();
        AltaEm = new javax.swing.JButton();
        Ventabtn = new javax.swing.JButton();
        Grupalbtn = new javax.swing.JButton();
        SeguiEn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        FondoP = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        Jlabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Salir = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AltaCl.setBackground(new java.awt.Color(255, 255, 255));
        AltaCl.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        AltaCl.setText("Alta de Clientes");
        AltaCl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AltaClActionPerformed(evt);
            }
        });
        jPanel2.add(AltaCl, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 220, 160));

        Comprabtn.setBackground(new java.awt.Color(255, 255, 255));
        Comprabtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Comprabtn.setText("Compra de Productos");
        Comprabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComprabtnActionPerformed(evt);
            }
        });
        jPanel2.add(Comprabtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 30, 210, 160));

        AltaEm.setBackground(new java.awt.Color(255, 255, 255));
        AltaEm.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        AltaEm.setText("Altas de Empleados");
        AltaEm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AltaEmActionPerformed(evt);
            }
        });
        jPanel2.add(AltaEm, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 220, 160));

        Ventabtn.setBackground(new java.awt.Color(255, 255, 255));
        Ventabtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Ventabtn.setText("Venta de Productos");
        jPanel2.add(Ventabtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 220, 210, 160));

        Grupalbtn.setBackground(new java.awt.Color(255, 255, 255));
        Grupalbtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Grupalbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GrupalbtnActionPerformed(evt);
            }
        });
        jPanel2.add(Grupalbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 220, 160));

        SeguiEn.setBackground(new java.awt.Color(255, 255, 255));
        SeguiEn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        SeguiEn.setText("Seguimiento del entrenador");
        jPanel2.add(SeguiEn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 220, 160));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(251, 153, 93));
        jLabel5.setText("Registro de clases Grupales");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Correo electronico:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(251, 153, 93));
        jLabel11.setText("Segimiento del Entrenador");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, -1, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(251, 153, 93));
        jLabel12.setText("Alta de Empelados");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(251, 153, 93));
        jLabel13.setText("Venta de Productos");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 380, -1, -1));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(251, 153, 93));
        jLabel14.setText("Alta de CLientes");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, -1, -1));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(251, 153, 93));
        jLabel15.setText("Compra de Productos");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 190, -1, -1));

        FondoP.setMaximumSize(new java.awt.Dimension(600, 282));
        FondoP.setMinimumSize(new java.awt.Dimension(600, 282));
        FondoP.setPreferredSize(new java.awt.Dimension(600, 282));
        FondoP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Foto de perfil del Empelado\\");
            FondoP.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 270, 230));

            jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
            jLabel2.setForeground(new java.awt.Color(255, 255, 255));
            jLabel2.setText("Id Empelado:");
            FondoP.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, -1, -1));

            jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
            jLabel3.setForeground(new java.awt.Color(255, 255, 255));
            jLabel3.setText("Nombre completo:");
            FondoP.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, -1));

            jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
            jLabel4.setForeground(new java.awt.Color(255, 255, 255));
            jLabel4.setText("Puesto:");
            FondoP.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, -1, -1));

            jTextField1.setText("56546");
            FondoP.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 139, -1));

            jTextField2.setText("kjbhj");
            FondoP.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 370, -1));

            jTextField3.setText("jj");
            FondoP.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 370, -1));

            jTextField4.setText("sss");
            FondoP.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 159, -1));

            Jlabel2.setBackground(new java.awt.Color(204, 255, 204));
            Jlabel2.setForeground(new java.awt.Color(204, 102, 0));
            Jlabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/IMAGENES JESUS/Commons_QR_code.png"))); // NOI18N
            Jlabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
            FondoP.add(Jlabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 40, 190, 190));

            jLabel6.setFont(new java.awt.Font("Eras Demi ITC", 0, 48)); // NOI18N
            jLabel6.setForeground(new java.awt.Color(255, 255, 255));
            jLabel6.setText("Hola,");
            FondoP.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

            jLabel8.setFont(new java.awt.Font("Eras Demi ITC", 1, 48)); // NOI18N
            jLabel8.setForeground(new java.awt.Color(251, 153, 93));
            jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel8.setText("Carlo!");
            FondoP.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, -1, -1));

            Salir.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
            Salir.setForeground(new java.awt.Color(255, 255, 255));
            Salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            Salir.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    SalirActionPerformed(evt);
                }
            });
            FondoP.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 10, 60, 60));

            jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
            jLabel10.setForeground(new java.awt.Color(255, 255, 255));
            jLabel10.setText("Correo electronico:");
            FondoP.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, -1, -1));

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(FondoP, javax.swing.GroupLayout.DEFAULT_SIZE, 1093, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(FondoP, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void GrupalbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GrupalbtnActionPerformed
        // TODO add your handling code here:
        RegistroClases Grupales = new RegistroClases();
        Grupales.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_GrupalbtnActionPerformed

    private void ComprabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComprabtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComprabtnActionPerformed

    private void AltaEmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AltaEmActionPerformed
        // TODO add your handling code here:
        RDE RegistroEmpleado= new RDE();
        RegistroEmpleado.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_AltaEmActionPerformed

    private void AltaClActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AltaClActionPerformed
        // TODO add your handling code here:
        registro_usuario cliente = new  registro_usuario();
        cliente.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AltaClActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Perfil_Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Perfil_Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Perfil_Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Perfil_Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Perfil_Empleado().setVisible(true);
            }
        });
    }
    
    
   
    
    
    

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AltaCl;
    private javax.swing.JButton AltaEm;
    private javax.swing.JButton Comprabtn;
    private javax.swing.JPanel FondoP;
    private javax.swing.JButton Grupalbtn;
    private javax.swing.JLabel Jlabel2;
    private javax.swing.JButton Salir;
    private javax.swing.JButton SeguiEn;
    private javax.swing.JButton Ventabtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
