/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gym_app;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;

/**
 *
 * @author ANDY
 */
public class Splash extends javax.swing.JFrame {

    /**
     * Creates new form INICIO
     */
    
    private Color Transparente;
    private Color Naranja, n;
    public Splash() {
        Transparente= new Color(0,0,0,0);
        Naranja= new Color(255,145,77);
        n= new Color(255, 251, 247);
        
        setUndecorated(true);//quita la barra de arriba
        initComponents();
        
        setLocationRelativeTo(null);
        setBackground(Transparente);
        
        ImageDecore Fondo = new ImageDecore(inicioback,"/Image/PowerGym.png");
        inicioback.add(Fondo).repaint();
        inicioback.setOpaque(true);
        inicioback.setForeground(Color.BLACK);
        inicioback.setBorder(null);
        inicioback.setBackground(Transparente);
        
        BarraProgreso();
        
        
    }

    
        private void BarraProgreso(){
            Timer tiempo= new Timer (45,(ActionEvent e) -> {
                
                int minProgress = BarraInicio.getValue();
                int maxProgress = BarraInicio.getMinimum();
                
                BarraInicio.setValue(BarraInicio.getValue()+1);
                BarraInicio.setBackground(n);
                
                BarraInicio.setStringPainted(true);
                BarraInicio.setString("Cargando..."+BarraInicio.getValue()+" %");
                
        /*        
                // Verificar si la barra de progreso ha alcanzado su valor máximo
        if (minProgress >= maxProgress) {
            tiempo.stop(); // Detener el temporizador si la barra de progreso ha finalizado
            
            
            
            
        } else {
            // Incrementar el valor de la barra de progreso si aún no ha alcanzado su máximo
            BarraInicio.setValue(minProgress + 1);
        }
*/
                
                
            });
            tiempo.start();
            
            
        }
        
      
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inicioback = new javax.swing.JPanel();
        BarraInicio = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BarraInicio.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 14)); // NOI18N
        BarraInicio.setForeground(new java.awt.Color(255, 145, 77));
        BarraInicio.setBorder(null);
        BarraInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));

        javax.swing.GroupLayout iniciobackLayout = new javax.swing.GroupLayout(inicioback);
        inicioback.setLayout(iniciobackLayout);
        iniciobackLayout.setHorizontalGroup(
            iniciobackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(iniciobackLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(BarraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        iniciobackLayout.setVerticalGroup(
            iniciobackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, iniciobackLayout.createSequentialGroup()
                .addGap(0, 470, Short.MAX_VALUE)
                .addComponent(BarraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(inicioback, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(inicioback, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Splash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar BarraInicio;
    private javax.swing.JPanel inicioback;
    // End of variables declaration//GEN-END:variables
}
